### ISSUE TITLE
Android 12.1 crash on sync

### ISSUE THREAD

**Issue by nukedupe** [fabienli/DokuwikiAndroid#67]
If i try to sync app crash.

- App version: 0.31 from f-droid
- Mobile: Poco F3
- Android OS: crDroidAndroid-12.1-20220715-alioth-v8.7

Log from logcat:
```
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.fabienli.dokuwiki, PID: 16061
E AndroidRuntime: java.lang.IllegalArgumentException: com.fabienli.dokuwiki: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E AndroidRuntime: Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E AndroidRuntime:        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E AndroidRuntime:        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
E AndroidRuntime:        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
E AndroidRuntime:        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
E AndroidRuntime:        at com.fabienli.dokuwiki.usecase.NotificationHandler.createNotification(NotificationHandler.java:39)
E AndroidRuntime:        at com.fabienli.dokuwiki.WikiCacheUiOrchestrator.updatePageListFromServer(WikiCacheUiOrchestrator.java:103)
E AndroidRuntime:        at com.fabienli.dokuwiki.MainActivity.onNavigationItemSelected(MainActivity.java:274)
E AndroidRuntime:        at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:285)
E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
E AndroidRuntime:        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
E AndroidRuntime:        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
E AndroidRuntime:        at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:485)
E AndroidRuntime:        at android.view.View.performClick(View.java:7455)
E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7432)
E AndroidRuntime:        at android.view.View.access$3700(View.java:835)
E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28810)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7833)
E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by nukedupe** [comment]
I tested the version from the Play Store (0.32). Everything works with this. Thanks for the quick fix.

**Comment by fabienli** [comment]
great !
thanks for this confirmation that the fix is working on a real device.
